FROM python:3.11

WORKDIR /app

COPY dashboard/requirements.txt .
RUN pip install -r requirements.txt

COPY dashboard/ ./dashboard/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0"]